


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: a0528075188-dev
  name: 'mysql'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: name
  replicas: 1
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: mysql-container
          image: >-
            mysql:8.0
          ports:
            - containerPort: 3306
              protocol: TCP
          env: 
           - name: MYSQL_ROOT_PASSWORD
             value: "1111"
           - name: MYSQL_DATABASE
             value: "test"
           - name: MYSQL_USER
             value: "shmuel"
           - name: MYSQL_PASSWORD
             value: "1234"

      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
